from check_privilege_syscat_views import *
from check_privilege_tablespaces import *
from check_privilege_group_entitlements import *
from check_privilege_secadm import *
from check_privilege_dbadm import *
from check_privilege_createtab import *
from check_privilege_bindadd import *
from check_privilege_connect import *
from check_privilege_nofence import *
from check_privilege_implschema import *
from check_privilege_load import *
from check_privilege_external_routine import *
from check_privilege_external_quiesceconnect import *
