from check_information_version import *
from check_configuration_audit_buffer import *
from check_configuration_authentication_mechanism import *
from check_configuration_catalog_noauth import *
from check_configuration_datalinks import *
from check_configuration_dftdbpath import *
from check_configuration_diaglevel import *
from check_configuration_diagpath import *
from check_configuration_discover import *
from check_configuration_discover_inst import *
from check_configuration_fed_noauth import *
from check_configuration_health_mon import *
from check_configuration_keepfenced import *
from check_configuration_notifylevel import *
from check_configuration_srvcon_auth import *
from check_privilege_syscat_views import *
from check_privilege_tablespaces import *
from check_privilege_group_entitlements import *
from check_privilege_secadm import *
from check_privilege_dbadm import *
from check_privilege_createtab import *
from check_privilege_bindadd import *
from check_privilege_connect import *
from check_privilege_nofence import *
from check_privilege_implschema import *
from check_privilege_load import *
from check_privilege_external_routine import *
from check_privilege_external_quiesceconnect import *
